config/routes.rb
Rails.application.routes.draw do

  root "contacts#index"
  resources :contacts do
    resources :tags, except: [:index, :show]
    resources :adresses, except: [:index, :show]
    resources :telephones, except: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
class Adress < ApplicationRecord

	belongs_to :contact

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

	has_many :telephones
	has_many :tags
	has_many :adresses

	mount_uploader :image, ImageUploader

end

app/models/tag.rb
class Tag < ApplicationRecord

	belongs_to :contact

end

app/models/telephone.rb
class Telephone < ApplicationRecord

	belongs_to :contact

end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: [:edit, :update, :destroy]


  # GET /adresses/new
  def new
    @adress = Adress.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses
  # POST /adresses.json
  def create
    @adress = Adress.new(adress_params)
    @adress.contact_id = params[:contact_id]
    @adress.save
  end

  # PATCH/PUT /adresses/1
  # PATCH/PUT /adresses/1.json
  def update
    @adress.update(adress_params)
  end

  # DELETE /adresses/1
  # DELETE /adresses/1.json
  def destroy
    @adress.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adress_params
      params.require(:adress).permit(:number, :number_type, :street, :city, :zip_code, :country, :contact_id, :apartment, :title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.save
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    @contact.update(contact_params)
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :title, :image)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    @tag.contact_id = params[:contact_id]
    @tag.save
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    @tag.update(tag_params)
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:title, :contact_id)
    end
end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  before_action :set_telephone, only: [:edit, :update, :destroy]


  # GET /telephones/new
  def new
    @telephone = Telephone.new
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)
    @telephone.contact_id = params[:contact_id]
    @telephone.save
  end

  # PATCH/PUT /telephones/1
  # PATCH/PUT /telephones/1.json
  def update
    @telephone.update(telephone_params)
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telephone_params
      params.require(:telephone).permit(:title, :number, :contact_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/adresses/_adress_row.html.erb
<% object = if params[:action] == "show" %>
  <% adress %>
<% elsif params[:action] == "create" || params[:action] == "update" %>
  <% @adress %>
<% end %>
<li id="adress_<%= object.id %>"><%= "#{object.title} : #{object.number} #{object.number_type}, #{object.street}, #{object.zip_code}, #{object.city}, #{object.country}" %> | <%= link_to "Edit adress", {:controller => "adresses", :action => "edit", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, remote: true %> | <%= link_to 'Delete adress', {:controller => "adresses", :action => "destroy", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
</li>

app/views/adresses/_form.html.erb
<div id="adress-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %> adress</h4>
      </div>
      <% url = if params[:action] == "edit" %>
      <% {:controller => "adresses", :action => "update"} %>
      <% elsif params[:action] == "new" %>
      <% contact_adresses_path %>
      <% end %>
      <%= form_for @adress, url: url, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :number %>
          <%= f.number_field :number, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :number_type %>
          <%= f.text_field :number_type, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :street %>
          <%= f.text_field :street, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :city %>
          <%= f.text_field :city, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :zip_code %>
          <%= f.text_field :zip_code, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :country %>
          <%= f.text_field :country, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :apartment %>
          <%= f.text_field :apartment, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/adresses/create.js.erb
<% if @adress.errors.blank? %>
  $('#adress-modal').modal('hide');
  $("#adresses").append('<%= j render "adress_row", adress: @adress %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/adresses/destroy.js.erb
$("#adress_<%=@adress.id%>").remove();

app/views/adresses/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/adresses/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/adresses/update.js.erb
<% if @adress.errors.blank? %>
  $('#adress-modal').modal('hide');
  $("#adress_<%=@adress.id%>").replaceWith('<%= j render "adress_row", adress: @adress %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/contacts/_contact_row.html.erb
<tr id="contact_<%= contact.id %>">
	<td><%= contact.first_name %></td>
	<td><%= contact.last_name %></td>
	<td><%= contact.title %></td>
	<td><% if contact.image.present? %>
		<%= image_tag contact.image.url(:small_thumb) %>
		<% end %></td>
	<td><% contact.telephones.each do |phone| %>
			<ul>
				<li><%= "#{phone.title} : #{phone.number}" %></li>
			</ul>
		<% end %></td>
	<td><% contact.adresses.each do |adress| %>
		<ul>
			<li><%= "#{adress.title} : #{adress.number}, #{adress.street}, #{adress.zip_code}, #{adress.city}, #{adress.country}" %></li>
		</ul>
	    <% end %></td>
	<td><% contact.tags.each do |tag| %>
		<ul>
			<li><%= tag.title %></li>
		</ul>
	    <% end %></td>
	<td><%= link_to 'Show contact', contact %> | 
	    <%= link_to "Edit contact", edit_contact_path(contact), remote: true %> | 
	    <%= link_to 'Delete contact', contact, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
</tr>

app/views/contacts/_form.html.erb
<div id="contact-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %> contact</h4>
      </div>
      <%= form_for @contact, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: "btn btn-default" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/create.js.erb
<% if @contact.errors.blank? %>
  $('#contact-modal').modal('hide');
  $('table tbody').append('<%= j render "contact_row", contact: @contact %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/contacts/destroy.js.erb
$("#contact_<%=@contact.id%>").remove();

app/views/contacts/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table class="table" id="contacts">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Title</th>
      <th>Image</th>
      <th>Telephone(s)</th>
      <th>Adress(es)</th>
      <th>Tag(s)</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <%= render 'contact_row', contact: contact %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Contact", new_contact_path, remote: true, class: "btn btn-primary" %>

<script>
$(document).ready(function() {
    $('#contacts').DataTable();
} );
</script>

app/views/contacts/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @contact.title %>
</p>

<p>
  <strong>Image:</strong>
  <% if @contact.image.present? %>
  <%= image_tag @contact.image.url(:thumb) %>
  <% end %>
</p>

<p>
  <strong>Telephone(s):</strong>
</p>
<ul id="telephones">
<% @contact.telephones.each do |phone| %>
  <%= render 'telephones/telephone_row', phone: phone %>
<% end %>
</ul>
<%= link_to "New telephone", new_contact_telephone_path(@contact), remote: true, class: "btn btn-primary" %>

<p>
  <strong>Adress(es):</strong>
</p>
<ul id="adresses">
<% @contact.adresses.each do |adress| %>
  <%= render 'adresses/adress_row', adress: adress %>
<% end %>
</ul>
<%= link_to "New adress", new_contact_adress_path(@contact), remote: true, class: "btn btn-primary" %>


<p>
  <strong>Tag(s):</strong>
</p>
<ul id="tags">
<% @contact.tags.each do |tag| %>
  <%= render 'tags/tag_row', tag: tag %>
<% end %>
</ul>
<%= link_to "New tag", new_contact_tag_path(@contact), remote: true, class: "btn btn-primary" %>
</p></br></br>

<%= link_to "Edit contact", edit_contact_path(@contact), remote: true %> |
<%= link_to 'Back to contacts', contacts_path %>

app/views/contacts/update.js.erb
<% if @contact.errors.blank? %>
  $('#contact-modal').modal('hide');
  $("#contact_<%=@contact.id%>").replaceWith('<%= j render "contact_row", contact: @contact %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactBase</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.html.erb
<div id="tag-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %> tag</h4>
      </div>
      <% url = if params[:action] == "edit" %>
        <% {:controller => "tags", :action => "update"} %>
      <% elsif params[:action] == "new" %>
        <% contact_tags_path %>
      <% end %>
      <%= form_for @tag, url: url, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control"%>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_tag_row.html.erb
<% object = if params[:action] == "show" %>
  <% tag %>
<% elsif params[:action] == "create" || params[:action] == "update" %>
  <% @tag %>
<% end %>
<li id="tag_<%= object.id %>"><%= object.title%> | <%= link_to "Edit tag", {:controller => "tags", :action => "edit", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, remote: true %> | <%= link_to 'Delete tag', {:controller => "tags", :action => "destroy", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
</li>

app/views/tags/create.js.erb
<% if @tag.errors.blank? %>
  $('#tag-modal').modal('hide');
  $("#tags").append('<%= j render "tag_row", tag: @tag %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/tags/destroy.js.erb
$("#tag_<%=@tag.id%>").remove();

app/views/tags/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/tags/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/tags/update.js.erb
<% if @tag.errors.blank? %>
  $('#tag-modal').modal('hide');
  $("#tag_<%=@tag.id%>").replaceWith('<%= j render "tag_row", tag: @tag %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/telephones/_form.html.erb
<div id="telephone-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= params[:action] %> telephone</h4>
      </div>
      <% url = if params[:action] == "edit" %>
        <% {:controller => "telephones", :action => "update"} %>
      <% elsif params[:action] == "new" %>
        <% contact_telephones_path %>
      <% end %>
      <%= form_for @telephone, url: url, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control"%>
          </div>

          <div class="form-group">
            <%= f.label :number %>
            <%= f.text_field :number, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/telephones/_telephone_row.html.erb
<% object = if params[:action] == "show" %>
  <% phone %>
<% elsif params[:action] == "create" || params[:action] == "update" %>
  <% @telephone %>
<% end %>
<li id="telephone_<%= object.id %>"><%= "#{object.title} : #{object.number}" %> | <%= link_to "Edit telephone", {:controller => "telephones", :action => "edit", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, remote: true %> | <%= link_to 'Delete telephone', {:controller => "telephones", :action => "destroy", :id => object.id, :contact_id => (params[:contact_id] || @contact.id)}, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
</li>

app/views/telephones/create.js.erb
<% if @telephone.errors.blank? %>
  $('#telephone-modal').modal('hide');
  $("#telephones").append('<%= j render "telephone_row", contact: @telephone %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>

app/views/telephones/destroy.js.erb
$("#telephone_<%=@telephone.id%>").remove();

app/views/telephones/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/telephones/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/telephones/update.js.erb
<% if @telephone.errors.blank? %>
  $('#telephone-modal').modal('hide');
  $("#telephone_<%=@telephone.id%>").replaceWith('<%= j render "telephone_row", telephone: @telephone %>');
<% else %>
  // TODO: show the errors in the UI
  alert('Algo falló');
<% end %>